version: "3.9"

services:
  web:
    build: .
    container_name: transcritor_web
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn transcritor_site.wsgi:application --bind 0.0.0.0:8001 --workers 1 --threads 2 --timeout 600 --worker-class=gthread"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file:
      - .env
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16G
        reservations:
          cpus: '0.5'
          memory: 8G 
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_DEVICE=cpu
      - GUNICORN_WORKERS=1
      - GUNICORN_THREADS=4
      - GUNICORN_TIMEOUT=300
    restart: unless-stopped
