version: "3.9"

services:
  web:
    build: .
    container_name: transcritor_web
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn transcritor_site.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    environment:
      - DEBUG=0
      - DJANGO_SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=192.168.1.19,localhost,127.0.0.1
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: transcritor_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - web
    restart: unless-stopped
